<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                exclude-result-prefixes="oracle-xsl-mapper xsi xsd xsl socket dvm mhdr oraxsl oraext xp20 xref">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source/>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets/>
    <!--GENERATED BY ORACLE XSL MAPPER 12.2.1.4.0(XSLT Build 190828.0353.3300) AT [SAT AUG 28 23:14:08 IST 2021].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <root>
      <divide>
        <xsl:value-of select="120 div 7"/>
      </divide>
      <multiply>
        <xsl:value-of select="120 * 7"/>
      </multiply>
      <add>
        <xsl:value-of select="120 + 7"/>
      </add>
      <subtract>
        <xsl:value-of select="120 - 7"/>
      </subtract>
      <square-root>
        <xsl:value-of select="oraext:square-root(121)"/>
      </square-root>
      <roundInt>
        <xsl:value-of select="round(17.64285714285714285714)"/>
      </roundInt>
      <roundDec1>
        <xsl:value-of select="round(17.64285714285714285714 * 100 ) div 100"/>
      </roundDec1>
      <floorInt>
        <xsl:value-of select="floor(17.64285714285714285714)"/>
      </floorInt>
      <floorDec1>
        <xsl:value-of select="floor(17.64285714285714285714 * 1000 ) div 1000"/>
      </floorDec1>
      <ceilInt>
        <xsl:value-of select="ceiling(17.14285714285714285714)"/>
      </ceilInt>
      <ceilDec1>
        <xsl:value-of select="ceiling(17.14285714285714285714 * 1000 ) div 1000"/>
      </ceilDec1>
      <format1>
        <xsl:value-of select="format-number(123.456, '#.00')"/>
      </format1>
      <format1-1>
        <xsl:value-of select="format-number(123.4, '#.00')"/>
      </format1-1>
      <format2>
        <xsl:value-of select="format-number(123.456, '#.##')"/>
      </format2>
      <format2-1>
        <xsl:value-of select="format-number(123, '#.##')"/>
      </format2-1>
      <format3>
        <xsl:value-of select="format-number(123456.789, '$#,###,###.00')"/>
      </format3>
      <format4>
        <xsl:value-of select="format-number(0.13245, '##.##%')"/>
      </format4>
      <format5>
        <xsl:value-of select="format-number(132.45, '#.000;(#.000)')"/>
      </format5>
      <format5-1>
        <xsl:value-of select="format-number(-132.45, '#.000;(#.000)')"/>
      </format5-1>
      <errors>
        <error>
          <xsl:value-of select="number('123 1')"/>
        </error>
        <error>
          <xsl:value-of select="number('abc')"/>
        </error>
        <error>
          <xsl:value-of select="number('123b')"/>
        </error>
      </errors>
    </root>
  </xsl:template>
</xsl:stylesheet>
